"""add vehicle_images table

Revision ID: 74cde196b244
Revises: d281d4e5eb46
Create Date: 2026-08-19 04:33:57.609765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74cde196b244'
down_revision: Union[str, None] = 'd281d4e5eb46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_images_vehicle_id'), 'vehicle_images', ['vehicle_id'], unique=False)

    # Data migration: copy existing vehicles.image_url to vehicle_images table
    connection = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(connection)
    if 'image_url' in [c['name'] for c in inspector.get_columns('vehicles')]:
        connection.execute(sa.text("""
            INSERT INTO vehicle_images (id, vehicle_id, image_url, sort_order, created_at)
            SELECT
                gen_random_uuid(),
                id,
                trim(unnest(string_to_array(vehicles.image_url, ','))),
                0,
                now()
            FROM vehicles
            WHERE image_url IS NOT NULL AND image_url != ''
        """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_images_vehicle_id'), table_name='vehicle_images')
    op.drop_table('vehicle_images')
    # ### end Alembic commands ###
