"""Add vehicle document tracking

Revision ID: d281d4e5eb46
Revises: dd3b0bd5d7e8
Create Date: 2026-08-13 02:29:49.204411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd281d4e5eb46'
down_revision: Union[str, None] = 'dd3b0bd5d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('assurance_expiry', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('vignette_expiry', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('visite_technique_expiry', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('carte_grise_expiry', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('autres_expiry', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('autres_label', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'autres_label')
    op.drop_column('vehicles', 'autres_expiry')
    op.drop_column('vehicles', 'carte_grise_expiry')
    op.drop_column('vehicles', 'visite_technique_expiry')
    op.drop_column('vehicles', 'vignette_expiry')
    op.drop_column('vehicles', 'assurance_expiry')
    # ### end Alembic commands ###
