name: Android Release

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Secrets
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          if [ -z "$STORE_PASSWORD" ]; then echo "STORE_PASSWORD MISSING"; else echo "STORE_PASSWORD AVAILABLE"; fi
          if [ -z "$KEY_PASSWORD" ]; then echo "KEY_PASSWORD MISSING"; else echo "KEY_PASSWORD AVAILABLE"; fi
          if [ -z "$KEYSTORE_BASE64" ]; then echo "KEYSTORE_BASE64 MISSING"; else echo "KEYSTORE_BASE64 AVAILABLE"; fi
